contone:

  outputs:
    dev:
      account: ik00045.ap-southeast-1
      database: FOUNDATIONAL_DB
      password: Gau@81294
      role: FOUNDATIONAL_ROLE
      schema: prod
      threads: 1
      type: snowflake
      user: gauravsnow
      warehouse: foundational_wh
  target: dev
